export const queryKeys = {
  me: ['me'] as const,
  branches: ['branches'] as const,
  periods: ['periods'] as const,
  master: (type: string) => ['master', type] as const,
  dashboard: (period: string, branch: string) => ['dashboard', period, branch] as const,
  expenses: (filters: string) => ['expenses', filters] as const,
  expense: (id: string) => ['expense', id] as const,
  budgets: (period: string) => ['budgets', period] as const,
  budget: (id: string) => ['budget', id] as const,
  report: (name: string, filters: string) => ['report', name, filters] as const,
  revenuePlans: (period: string) => ['revenue-plans', period] as const,
  revenuePlan: (id: string) => ['revenue-plan', id] as const,
  revenueTransactions: (filters: string) => ['revenue-transactions', filters] as const,
  revenueTransaction: (id: string) => ['revenue-transaction', id] as const,
  dataQuality: (filters: string) => ['data-quality', filters] as const,
  periodReadiness: (id: string) => ['period-readiness', id] as const,
  userDirectory: ['user-directory'] as const,
  users: ['users'] as const,
  audit: (filters: string) => ['audit', filters] as const,
};
